namespace Constants.Enums;

public enum Category
{
    None,
    Antiques,
    Apparel,
    ArtCollectibles,
    ArtSupplies,
    Automotive,
    BabyProducts,
    BeautyPersonalCare,
    Books,
    CamerasPhotography,
    CraftSupplies,
    Electronics,
    FarmingAgriculture,
    FoodBeverages,
    Gaming,
    Health,
    HomeGarden,
    IndustrialSupplies,
    Jewelry,
    Kitchenware,
    MusicEquipment,
    OfficeSupplies,
    OutdoorEquipment,
    Pets,
    RealEstate,
    Sports,
    Technology,
    Tools,
    Toys,
    TravelEquipment,
    Vintage,
    Education
}