version: '3.8'

services:
  trade-market:
    image: trade-market
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:80"
    volumes:
      - trade-market-images:/app/wwwroot/images

volumes:
  trade-market-images:
