version: '3.8'

services:
  trade-market:
    image: trade-market
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:80"
  
  trade-market-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'S3cur3P@ssW0rd!'
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr &
        for i in {1..50};
        do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'S3cur3P@ssW0rd!' -Q 'SELECT 1' && break || sleep 1;
        done
        if [ $$? -eq 0 ]
        then
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'S3cur3P@ssW0rd!' -i /docker-entrypoint-initdb.d/init.sql
        else
          echo 'SQL Server took too long to start, initialization script was not executed.'
          exit 1
        fi
        wait
      "

volumes:
  mssql_data:
    driver: local
  